#:schema https://mago.carthage.software/1.30.0/schema.json
version = "1"
php-version = "8.3.0"

[source]
workspace = "."
paths = ["packages", "config"]
includes = ["vendor"]
excludes = ["Public/**", "node_modules/**", "config/system/settings.php", "packages/fluid-primitives/public", "packages/fluid-primitives/vendor"]

[formatter]
preset = "default"
space-after-cast-unary-prefix-operators = false
line-before-binary-operator = false
indent-heredoc = false

[linter]
integrations = ["symfony"]

[linter.rules]
too-many-methods = { threshold = 15 }
cyclomatic-complexity = { threshold = 35 }
kan-defect = { threshold = 3 }
no-boolean-flag-parameter = { enabled = false }
no-shorthand-ternary = { enabled = false }
readable-literal = { enabled = false }
tagged-todo = { enabled = false }
literal-named-argument = { enabled = false}
no-else-clause = { enabled = false }
no-isset = { enabled = false }
no-global = { enabled = false }