#:schema https://mago.carthage.software/1.48.1/schema.json
version = "1"
php-version = "8.2.0"

[source]
workspace = "."
paths = ["packages", "config"]
includes = ["vendor"]
excludes = [
    "Public/**", 
    "node_modules/**", 
    "config/system/settings.php", 
    "packages/fluid-primitives/public", 
    "packages/fluid-primitives/vendor", 
    "**/*.svg",
    "**/*.xlf",
]

[formatter]
preset = "default"
space-after-cast-unary-prefix-operators = false
line-before-binary-operator = false
indent-heredoc = false

[linter]
integrations = ["symfony"]
excludes = ["packages/fluid-primitives/tests/**"]

[linter.rules]
no-shorthand-ternary = { enabled = false }
readable-literal = { enabled = false }
tagged-todo = { enabled = false }
cyclomatic-complexity = { threshold = 25 }
kan-defect = { threshold = 1.7 }
no-boolean-flag-parameter = { enabled = false }
excessive-parameter-list = { threshold = 5, constructor-threshold = 10 }

[analyzer]
ignore = ["invalid-type-cast"]
excludes = ["packages/fluid-primitives/tests/**"]