// AUTO-GENERATED by `ui:generate-hydration-types` - do not edit by hand.
export type CommandMenuHydrationProps =
    { id: string; ids: Record<string, string> } &
    { searchUrl: string };

declare module 'fluid-primitives/client' {
    interface HydrationPropsRegistry {
        commandMenu: CommandMenuHydrationProps;
    }
}
