import { AccordionHydrationProps, AccordionExamplesAllHydrationProps, AccordionExamplesDisabledHydrationProps, AccordionExamplesMultipleHydrationProps, AccordionExamplesSimpleHydrationProps, AlertHydrationProps, ButtonHydrationProps, CheckboxHydrationProps, CheckboxExamplesAllHydrationProps, CheckboxExamplesDefaultCheckedHydrationProps, CheckboxExamplesDisabledHydrationProps, CheckboxExamplesIndeterminateHydrationProps, CheckboxExamplesSimpleHydrationProps, CheckboxGroupHydrationProps, CheckboxGroupExamplesAllHydrationProps, CheckboxGroupExamplesDefaultCheckedHydrationProps, CheckboxGroupExamplesDisabledGroupHydrationProps, CheckboxGroupExamplesDisabledItemsHydrationProps, CheckboxGroupExamplesMaxSelectedHydrationProps, CheckboxGroupExamplesSelectAllHydrationProps, CheckboxGroupExamplesSimpleHydrationProps, ClipboardHydrationProps, ClipboardExamplesAllHydrationProps, ClipboardExamplesCopyButtonOnlyHydrationProps, ClipboardExamplesCustomTimeoutHydrationProps, ClipboardExamplesSimpleHydrationProps, CollapsibleHydrationProps, CollapsibleExamplesAllHydrationProps, CollapsibleExamplesDefaultOpenHydrationProps, CollapsibleExamplesDisabledHydrationProps, CollapsibleExamplesSimpleHydrationProps, ComboboxHydrationProps, ComboboxExamplesAllHydrationProps, ComboboxExamplesAsyncSearchHydrationProps, ComboboxExamplesAsyncSearchGroupedHydrationProps, ComboboxExamplesCustomFilterApiHydrationProps, ComboboxExamplesDefaultValueHydrationProps, ComboboxExamplesDisabledItemsHydrationProps, ComboboxExamplesMultipleHydrationProps, ComboboxExamplesSimpleHydrationProps, ComboboxExamplesWithFieldHydrationProps, ComboboxExamplesWithGroupsHydrationProps, DialogHydrationProps, DialogExamplesAlertHydrationProps, DialogExamplesAllHydrationProps, DialogExamplesInsideScrollHydrationProps, DialogExamplesNestedHydrationProps, DialogExamplesOutsideScrollHydrationProps, DialogExamplesPreventCloseEscapeHydrationProps, DialogExamplesPreventCloseOutsideHydrationProps, DialogExamplesSimpleHydrationProps, DialogExamplesWithPopoverHydrationProps, FieldHydrationProps, FieldArrayHydrationProps, FieldArrayExamplesAllHydrationProps, FieldArrayExamplesEmptyHydrationProps, FieldArrayExamplesLimitedHydrationProps, FieldArrayExamplesSimpleHydrationProps, FieldExamplesAllHydrationProps, FieldExamplesDisabledHydrationProps, FieldExamplesInvalidHydrationProps, FieldExamplesRequiredHydrationProps, FieldExamplesSimpleHydrationProps, FieldExamplesWithCheckboxHydrationProps, FieldExamplesWithDescriptionHydrationProps, FileUploadHydrationProps, FileUploadExamplesAllHydrationProps, FileUploadExamplesCustomLayoutHydrationProps, FileUploadExamplesDeleteConfirmationHydrationProps, FileUploadExamplesDirectoryHydrationProps, FileUploadExamplesRejectedFilesHydrationProps, FileUploadExamplesSimpleHydrationProps, FileUploadExamplesWithFieldHydrationProps, FormHydrationProps, IconCheckHydrationProps, IconChevronDownHydrationProps, IconCopyHydrationProps, IconGithubHydrationProps, IconInfoHydrationProps, IconListToggleHydrationProps, IconMenuHydrationProps, IconMoveRightHydrationProps, IconSearchHydrationProps, IconTocHydrationProps, IconXHydrationProps, InputHydrationProps, InputExamplesAllHydrationProps, InputExamplesSimpleHydrationProps, InputExamplesWithFieldHydrationProps, InputExamplesWordCountHydrationProps, MenuHydrationProps, MenuExamplesAllHydrationProps, MenuExamplesContextMenuHydrationProps, MenuExamplesGroupingHydrationProps, MenuExamplesInsideDialogHydrationProps, MenuExamplesMultipleTriggersHydrationProps, MenuExamplesNestedHydrationProps, MenuExamplesSimpleHydrationProps, MenuExamplesWithCheckboxesHydrationProps, MenuExamplesWithLinksHydrationProps, MenuExamplesWithRadiosHydrationProps, NavigationMenuHydrationProps, NavigationMenuExamplesAllHydrationProps, NavigationMenuExamplesSimpleHydrationProps, NavigationMenuExamplesWithLinksHydrationProps, NavigationMenuExamplesWithViewportHydrationProps, NumberInputHydrationProps, NumberInputExamplesAllHydrationProps, NumberInputExamplesFormatOptionsHydrationProps, NumberInputExamplesMinMaxHydrationProps, NumberInputExamplesMouseWheelHydrationProps, NumberInputExamplesSimpleHydrationProps, NumberInputExamplesWithScrubberHydrationProps, PopoverHydrationProps, PopoverExamplesAllHydrationProps, PopoverExamplesCustomPositioningHydrationProps, PopoverExamplesModalHydrationProps, PopoverExamplesSimpleHydrationProps, PopoverExamplesWithCloseButtonHydrationProps, RadioGroupHydrationProps, RadioGroupExamplesAllHydrationProps, RadioGroupExamplesDisabledGroupHydrationProps, RadioGroupExamplesDisabledItemsHydrationProps, RadioGroupExamplesNoDefaultHydrationProps, RadioGroupExamplesSimpleHydrationProps, ScrollAreaHydrationProps, ScrollAreaExamplesAllHydrationProps, ScrollAreaExamplesBothDirectionsHydrationProps, ScrollAreaExamplesHorizontalHydrationProps, ScrollAreaExamplesSimpleHydrationProps, SelectHydrationProps, SelectExamplesAllHydrationProps, SelectExamplesDefaultValueHydrationProps, SelectExamplesDisabledItemsHydrationProps, SelectExamplesMultipleHydrationProps, SelectExamplesSimpleHydrationProps, SelectExamplesWithFieldHydrationProps, SelectExamplesWithGroupsHydrationProps, SliderHydrationProps, SliderExamplesAllHydrationProps, SliderExamplesDisabledHydrationProps, SliderExamplesRangeHydrationProps, SliderExamplesSimpleHydrationProps, SliderExamplesWithDecimalValuesHydrationProps, SliderExamplesWithDraggingIndicatorHydrationProps, SliderExamplesWithFieldHydrationProps, SliderExamplesWithMarksHydrationProps, SliderExamplesWithNumberInputHydrationProps, SwitchHydrationProps, SwitchExamplesAllHydrationProps, SwitchExamplesDefaultCheckedHydrationProps, SwitchExamplesDisabledHydrationProps, SwitchExamplesSimpleHydrationProps, SwitchExamplesWithFieldHydrationProps, TabsHydrationProps, TabsExamplesAllHydrationProps, TabsExamplesDisabledTabsHydrationProps, TabsExamplesManualActivationHydrationProps, TabsExamplesSimpleHydrationProps, TabsExamplesVerticalHydrationProps, TextareaHydrationProps, TextareaExamplesAllHydrationProps, TextareaExamplesSimpleHydrationProps, TextareaExamplesWithFieldHydrationProps, TextareaExamplesWordCountHydrationProps, TooltipHydrationProps, TooltipExamplesAllHydrationProps, TooltipExamplesCloseDelayHydrationProps, TooltipExamplesCustomPositioningHydrationProps, TooltipExamplesDisabledHydrationProps, TooltipExamplesIconButtonHydrationProps, TooltipExamplesMultipleNoDelayHydrationProps, TooltipExamplesOpenDelayHydrationProps, TooltipExamplesSimpleHydrationProps, CommandMenuHydrationProps, ComponentExampleHydrationProps, ComponentPropsTableHydrationProps, CounterHydrationProps, EditEventRegistrationHydrationProps, EventRegistrationHydrationProps, FormExampleHydrationProps, GuestListHydrationProps, HomeSectionTitleHydrationProps, InstallationSectionHydrationProps, NavigationHydrationProps, PasswordConfirmationHydrationProps, ReferenceButtonsHydrationProps, SkipNavLinkHydrationProps, TextareaSubmitOnEnterExampleHydrationProps, TextareaTransformExampleHydrationProps, TransformExampleHydrationProps } from './ui/index.d';
import { AccordionHydrationProps as AccordionHydrationPropsImport, CheckboxHydrationProps as CheckboxHydrationPropsImport, CheckboxGroupHydrationProps as CheckboxGroupHydrationPropsImport, ClipboardHydrationProps as ClipboardHydrationPropsImport, CollapsibleHydrationProps as CollapsibleHydrationPropsImport, ComboboxHydrationProps as ComboboxHydrationPropsImport, DialogHydrationProps as DialogHydrationPropsImport, FieldHydrationProps as FieldHydrationPropsImport, FieldArrayHydrationProps as FieldArrayHydrationPropsImport, FileUploadHydrationProps as FileUploadHydrationPropsImport, FormHydrationProps as FormHydrationPropsImport, InputHydrationProps as InputHydrationPropsImport, MenuHydrationProps as MenuHydrationPropsImport, NavigationMenuHydrationProps as NavigationMenuHydrationPropsImport, NumberInputHydrationProps as NumberInputHydrationPropsImport, PopoverHydrationProps as PopoverHydrationPropsImport, RadioGroupHydrationProps as RadioGroupHydrationPropsImport, ScrollAreaHydrationProps as ScrollAreaHydrationPropsImport, SelectHydrationProps as SelectHydrationPropsImport, SliderHydrationProps as SliderHydrationPropsImport, SwitchHydrationProps as SwitchHydrationPropsImport, TabsHydrationProps as TabsHydrationPropsImport, TextareaHydrationProps as TextareaHydrationPropsImport, TooltipHydrationProps as TooltipHydrationPropsImport } from './primitives/index.d';
import { AccordionHydrationProps as AccordionHydrationPropsImport2, CheckboxHydrationProps as CheckboxHydrationPropsImport2, InputHydrationProps as InputHydrationPropsImport2, SelectHydrationProps as SelectHydrationPropsImport2, VanillaAccordionHydrationProps, VanillaCheckboxHydrationProps, VanillaInputHydrationProps, VanillaSelectHydrationProps } from './bench/index.d';
declare module 'fluid-primitives' {
    interface HydrationPropsRegistry {
        "ui:accordion": AccordionHydrationProps;
        "ui:accordionExamples.all": AccordionExamplesAllHydrationProps;
        "ui:accordionExamples.disabled": AccordionExamplesDisabledHydrationProps;
        "ui:accordionExamples.multiple": AccordionExamplesMultipleHydrationProps;
        "ui:accordionExamples.simple": AccordionExamplesSimpleHydrationProps;
        "ui:alert": AlertHydrationProps;
        "ui:button": ButtonHydrationProps;
        "ui:checkbox": CheckboxHydrationProps;
        "ui:checkboxExamples.all": CheckboxExamplesAllHydrationProps;
        "ui:checkboxExamples.defaultChecked": CheckboxExamplesDefaultCheckedHydrationProps;
        "ui:checkboxExamples.disabled": CheckboxExamplesDisabledHydrationProps;
        "ui:checkboxExamples.indeterminate": CheckboxExamplesIndeterminateHydrationProps;
        "ui:checkboxExamples.simple": CheckboxExamplesSimpleHydrationProps;
        "ui:checkboxGroup": CheckboxGroupHydrationProps;
        "ui:checkboxGroupExamples.all": CheckboxGroupExamplesAllHydrationProps;
        "ui:checkboxGroupExamples.defaultChecked": CheckboxGroupExamplesDefaultCheckedHydrationProps;
        "ui:checkboxGroupExamples.disabledGroup": CheckboxGroupExamplesDisabledGroupHydrationProps;
        "ui:checkboxGroupExamples.disabledItems": CheckboxGroupExamplesDisabledItemsHydrationProps;
        "ui:checkboxGroupExamples.maxSelected": CheckboxGroupExamplesMaxSelectedHydrationProps;
        "ui:checkboxGroupExamples.selectAll": CheckboxGroupExamplesSelectAllHydrationProps;
        "ui:checkboxGroupExamples.simple": CheckboxGroupExamplesSimpleHydrationProps;
        "ui:clipboard": ClipboardHydrationProps;
        "ui:clipboardExamples.all": ClipboardExamplesAllHydrationProps;
        "ui:clipboardExamples.copyButtonOnly": ClipboardExamplesCopyButtonOnlyHydrationProps;
        "ui:clipboardExamples.customTimeout": ClipboardExamplesCustomTimeoutHydrationProps;
        "ui:clipboardExamples.simple": ClipboardExamplesSimpleHydrationProps;
        "ui:collapsible": CollapsibleHydrationProps;
        "ui:collapsibleExamples.all": CollapsibleExamplesAllHydrationProps;
        "ui:collapsibleExamples.defaultOpen": CollapsibleExamplesDefaultOpenHydrationProps;
        "ui:collapsibleExamples.disabled": CollapsibleExamplesDisabledHydrationProps;
        "ui:collapsibleExamples.simple": CollapsibleExamplesSimpleHydrationProps;
        "ui:combobox": ComboboxHydrationProps;
        "ui:comboboxExamples.all": ComboboxExamplesAllHydrationProps;
        "ui:comboboxExamples.asyncSearch": ComboboxExamplesAsyncSearchHydrationProps;
        "ui:comboboxExamples.asyncSearchGrouped": ComboboxExamplesAsyncSearchGroupedHydrationProps;
        "ui:comboboxExamples.customFilterApi": ComboboxExamplesCustomFilterApiHydrationProps;
        "ui:comboboxExamples.defaultValue": ComboboxExamplesDefaultValueHydrationProps;
        "ui:comboboxExamples.disabledItems": ComboboxExamplesDisabledItemsHydrationProps;
        "ui:comboboxExamples.multiple": ComboboxExamplesMultipleHydrationProps;
        "ui:comboboxExamples.simple": ComboboxExamplesSimpleHydrationProps;
        "ui:comboboxExamples.withField": ComboboxExamplesWithFieldHydrationProps;
        "ui:comboboxExamples.withGroups": ComboboxExamplesWithGroupsHydrationProps;
        "ui:dialog": DialogHydrationProps;
        "ui:dialogExamples.alert": DialogExamplesAlertHydrationProps;
        "ui:dialogExamples.all": DialogExamplesAllHydrationProps;
        "ui:dialogExamples.insideScroll": DialogExamplesInsideScrollHydrationProps;
        "ui:dialogExamples.nested": DialogExamplesNestedHydrationProps;
        "ui:dialogExamples.outsideScroll": DialogExamplesOutsideScrollHydrationProps;
        "ui:dialogExamples.preventCloseEscape": DialogExamplesPreventCloseEscapeHydrationProps;
        "ui:dialogExamples.preventCloseOutside": DialogExamplesPreventCloseOutsideHydrationProps;
        "ui:dialogExamples.simple": DialogExamplesSimpleHydrationProps;
        "ui:dialogExamples.withPopover": DialogExamplesWithPopoverHydrationProps;
        "ui:field": FieldHydrationProps;
        "ui:fieldArray": FieldArrayHydrationProps;
        "ui:fieldArrayExamples.all": FieldArrayExamplesAllHydrationProps;
        "ui:fieldArrayExamples.empty": FieldArrayExamplesEmptyHydrationProps;
        "ui:fieldArrayExamples.limited": FieldArrayExamplesLimitedHydrationProps;
        "ui:fieldArrayExamples.simple": FieldArrayExamplesSimpleHydrationProps;
        "ui:fieldExamples.all": FieldExamplesAllHydrationProps;
        "ui:fieldExamples.disabled": FieldExamplesDisabledHydrationProps;
        "ui:fieldExamples.invalid": FieldExamplesInvalidHydrationProps;
        "ui:fieldExamples.required": FieldExamplesRequiredHydrationProps;
        "ui:fieldExamples.simple": FieldExamplesSimpleHydrationProps;
        "ui:fieldExamples.withCheckbox": FieldExamplesWithCheckboxHydrationProps;
        "ui:fieldExamples.withDescription": FieldExamplesWithDescriptionHydrationProps;
        "ui:fileUpload": FileUploadHydrationProps;
        "ui:fileUploadExamples.all": FileUploadExamplesAllHydrationProps;
        "ui:fileUploadExamples.customLayout": FileUploadExamplesCustomLayoutHydrationProps;
        "ui:fileUploadExamples.deleteConfirmation": FileUploadExamplesDeleteConfirmationHydrationProps;
        "ui:fileUploadExamples.directory": FileUploadExamplesDirectoryHydrationProps;
        "ui:fileUploadExamples.rejectedFiles": FileUploadExamplesRejectedFilesHydrationProps;
        "ui:fileUploadExamples.simple": FileUploadExamplesSimpleHydrationProps;
        "ui:fileUploadExamples.withField": FileUploadExamplesWithFieldHydrationProps;
        "ui:form": FormHydrationProps;
        "ui:icon.check": IconCheckHydrationProps;
        "ui:icon.chevronDown": IconChevronDownHydrationProps;
        "ui:icon.copy": IconCopyHydrationProps;
        "ui:icon.github": IconGithubHydrationProps;
        "ui:icon.info": IconInfoHydrationProps;
        "ui:icon.listToggle": IconListToggleHydrationProps;
        "ui:icon.menu": IconMenuHydrationProps;
        "ui:icon.moveRight": IconMoveRightHydrationProps;
        "ui:icon.search": IconSearchHydrationProps;
        "ui:icon.toc": IconTocHydrationProps;
        "ui:icon.x": IconXHydrationProps;
        "ui:input": InputHydrationProps;
        "ui:inputExamples.all": InputExamplesAllHydrationProps;
        "ui:inputExamples.simple": InputExamplesSimpleHydrationProps;
        "ui:inputExamples.withField": InputExamplesWithFieldHydrationProps;
        "ui:inputExamples.wordCount": InputExamplesWordCountHydrationProps;
        "ui:menu": MenuHydrationProps;
        "ui:menuExamples.all": MenuExamplesAllHydrationProps;
        "ui:menuExamples.contextMenu": MenuExamplesContextMenuHydrationProps;
        "ui:menuExamples.grouping": MenuExamplesGroupingHydrationProps;
        "ui:menuExamples.insideDialog": MenuExamplesInsideDialogHydrationProps;
        "ui:menuExamples.multipleTriggers": MenuExamplesMultipleTriggersHydrationProps;
        "ui:menuExamples.nested": MenuExamplesNestedHydrationProps;
        "ui:menuExamples.simple": MenuExamplesSimpleHydrationProps;
        "ui:menuExamples.withCheckboxes": MenuExamplesWithCheckboxesHydrationProps;
        "ui:menuExamples.withLinks": MenuExamplesWithLinksHydrationProps;
        "ui:menuExamples.withRadios": MenuExamplesWithRadiosHydrationProps;
        "ui:navigationMenu": NavigationMenuHydrationProps;
        "ui:navigationMenuExamples.all": NavigationMenuExamplesAllHydrationProps;
        "ui:navigationMenuExamples.simple": NavigationMenuExamplesSimpleHydrationProps;
        "ui:navigationMenuExamples.withLinks": NavigationMenuExamplesWithLinksHydrationProps;
        "ui:navigationMenuExamples.withViewport": NavigationMenuExamplesWithViewportHydrationProps;
        "ui:numberInput": NumberInputHydrationProps;
        "ui:numberInputExamples.all": NumberInputExamplesAllHydrationProps;
        "ui:numberInputExamples.formatOptions": NumberInputExamplesFormatOptionsHydrationProps;
        "ui:numberInputExamples.minMax": NumberInputExamplesMinMaxHydrationProps;
        "ui:numberInputExamples.mouseWheel": NumberInputExamplesMouseWheelHydrationProps;
        "ui:numberInputExamples.simple": NumberInputExamplesSimpleHydrationProps;
        "ui:numberInputExamples.withScrubber": NumberInputExamplesWithScrubberHydrationProps;
        "ui:popover": PopoverHydrationProps;
        "ui:popoverExamples.all": PopoverExamplesAllHydrationProps;
        "ui:popoverExamples.customPositioning": PopoverExamplesCustomPositioningHydrationProps;
        "ui:popoverExamples.modal": PopoverExamplesModalHydrationProps;
        "ui:popoverExamples.simple": PopoverExamplesSimpleHydrationProps;
        "ui:popoverExamples.withCloseButton": PopoverExamplesWithCloseButtonHydrationProps;
        "ui:radioGroup": RadioGroupHydrationProps;
        "ui:radioGroupExamples.all": RadioGroupExamplesAllHydrationProps;
        "ui:radioGroupExamples.disabledGroup": RadioGroupExamplesDisabledGroupHydrationProps;
        "ui:radioGroupExamples.disabledItems": RadioGroupExamplesDisabledItemsHydrationProps;
        "ui:radioGroupExamples.noDefault": RadioGroupExamplesNoDefaultHydrationProps;
        "ui:radioGroupExamples.simple": RadioGroupExamplesSimpleHydrationProps;
        "ui:scrollArea": ScrollAreaHydrationProps;
        "ui:scrollAreaExamples.all": ScrollAreaExamplesAllHydrationProps;
        "ui:scrollAreaExamples.bothDirections": ScrollAreaExamplesBothDirectionsHydrationProps;
        "ui:scrollAreaExamples.horizontal": ScrollAreaExamplesHorizontalHydrationProps;
        "ui:scrollAreaExamples.simple": ScrollAreaExamplesSimpleHydrationProps;
        "ui:select": SelectHydrationProps;
        "ui:selectExamples.all": SelectExamplesAllHydrationProps;
        "ui:selectExamples.defaultValue": SelectExamplesDefaultValueHydrationProps;
        "ui:selectExamples.disabledItems": SelectExamplesDisabledItemsHydrationProps;
        "ui:selectExamples.multiple": SelectExamplesMultipleHydrationProps;
        "ui:selectExamples.simple": SelectExamplesSimpleHydrationProps;
        "ui:selectExamples.withField": SelectExamplesWithFieldHydrationProps;
        "ui:selectExamples.withGroups": SelectExamplesWithGroupsHydrationProps;
        "ui:slider": SliderHydrationProps;
        "ui:sliderExamples.all": SliderExamplesAllHydrationProps;
        "ui:sliderExamples.disabled": SliderExamplesDisabledHydrationProps;
        "ui:sliderExamples.range": SliderExamplesRangeHydrationProps;
        "ui:sliderExamples.simple": SliderExamplesSimpleHydrationProps;
        "ui:sliderExamples.withDecimalValues": SliderExamplesWithDecimalValuesHydrationProps;
        "ui:sliderExamples.withDraggingIndicator": SliderExamplesWithDraggingIndicatorHydrationProps;
        "ui:sliderExamples.withField": SliderExamplesWithFieldHydrationProps;
        "ui:sliderExamples.withMarks": SliderExamplesWithMarksHydrationProps;
        "ui:sliderExamples.withNumberInput": SliderExamplesWithNumberInputHydrationProps;
        "ui:switch": SwitchHydrationProps;
        "ui:switchExamples.all": SwitchExamplesAllHydrationProps;
        "ui:switchExamples.defaultChecked": SwitchExamplesDefaultCheckedHydrationProps;
        "ui:switchExamples.disabled": SwitchExamplesDisabledHydrationProps;
        "ui:switchExamples.simple": SwitchExamplesSimpleHydrationProps;
        "ui:switchExamples.withField": SwitchExamplesWithFieldHydrationProps;
        "ui:tabs": TabsHydrationProps;
        "ui:tabsExamples.all": TabsExamplesAllHydrationProps;
        "ui:tabsExamples.disabledTabs": TabsExamplesDisabledTabsHydrationProps;
        "ui:tabsExamples.manualActivation": TabsExamplesManualActivationHydrationProps;
        "ui:tabsExamples.simple": TabsExamplesSimpleHydrationProps;
        "ui:tabsExamples.vertical": TabsExamplesVerticalHydrationProps;
        "ui:textarea": TextareaHydrationProps;
        "ui:textareaExamples.all": TextareaExamplesAllHydrationProps;
        "ui:textareaExamples.simple": TextareaExamplesSimpleHydrationProps;
        "ui:textareaExamples.withField": TextareaExamplesWithFieldHydrationProps;
        "ui:textareaExamples.wordCount": TextareaExamplesWordCountHydrationProps;
        "ui:tooltip": TooltipHydrationProps;
        "ui:tooltipExamples.all": TooltipExamplesAllHydrationProps;
        "ui:tooltipExamples.closeDelay": TooltipExamplesCloseDelayHydrationProps;
        "ui:tooltipExamples.customPositioning": TooltipExamplesCustomPositioningHydrationProps;
        "ui:tooltipExamples.disabled": TooltipExamplesDisabledHydrationProps;
        "ui:tooltipExamples.iconButton": TooltipExamplesIconButtonHydrationProps;
        "ui:tooltipExamples.multipleNoDelay": TooltipExamplesMultipleNoDelayHydrationProps;
        "ui:tooltipExamples.openDelay": TooltipExamplesOpenDelayHydrationProps;
        "ui:tooltipExamples.simple": TooltipExamplesSimpleHydrationProps;
        "ui:commandMenu": CommandMenuHydrationProps;
        "ui:componentExample": ComponentExampleHydrationProps;
        "ui:componentPropsTable": ComponentPropsTableHydrationProps;
        "ui:counter": CounterHydrationProps;
        "ui:editEventRegistration": EditEventRegistrationHydrationProps;
        "ui:eventRegistration": EventRegistrationHydrationProps;
        "ui:formExample": FormExampleHydrationProps;
        "ui:guestList": GuestListHydrationProps;
        "ui:homeSectionTitle": HomeSectionTitleHydrationProps;
        "ui:installationSection": InstallationSectionHydrationProps;
        "ui:navigation": NavigationHydrationProps;
        "ui:passwordConfirmation": PasswordConfirmationHydrationProps;
        "ui:referenceButtons": ReferenceButtonsHydrationProps;
        "ui:skipNavLink": SkipNavLinkHydrationProps;
        "ui:textareaSubmitOnEnterExample": TextareaSubmitOnEnterExampleHydrationProps;
        "ui:textareaTransformExample": TextareaTransformExampleHydrationProps;
        "ui:transformExample": TransformExampleHydrationProps;
        "primitives:accordion": AccordionHydrationPropsImport;
        "primitives:checkbox": CheckboxHydrationPropsImport;
        "primitives:checkboxGroup": CheckboxGroupHydrationPropsImport;
        "primitives:clipboard": ClipboardHydrationPropsImport;
        "primitives:collapsible": CollapsibleHydrationPropsImport;
        "primitives:combobox": ComboboxHydrationPropsImport;
        "primitives:dialog": DialogHydrationPropsImport;
        "primitives:field": FieldHydrationPropsImport;
        "primitives:fieldArray": FieldArrayHydrationPropsImport;
        "primitives:fileUpload": FileUploadHydrationPropsImport;
        "primitives:form": FormHydrationPropsImport;
        "primitives:input": InputHydrationPropsImport;
        "primitives:menu": MenuHydrationPropsImport;
        "primitives:navigationMenu": NavigationMenuHydrationPropsImport;
        "primitives:numberInput": NumberInputHydrationPropsImport;
        "primitives:popover": PopoverHydrationPropsImport;
        "primitives:radioGroup": RadioGroupHydrationPropsImport;
        "primitives:scrollArea": ScrollAreaHydrationPropsImport;
        "primitives:select": SelectHydrationPropsImport;
        "primitives:slider": SliderHydrationPropsImport;
        "primitives:switch": SwitchHydrationPropsImport;
        "primitives:tabs": TabsHydrationPropsImport;
        "primitives:textarea": TextareaHydrationPropsImport;
        "primitives:tooltip": TooltipHydrationPropsImport;
        "bench:accordion": AccordionHydrationPropsImport2;
        "bench:checkbox": CheckboxHydrationPropsImport2;
        "bench:input": InputHydrationPropsImport2;
        "bench:select": SelectHydrationPropsImport2;
        "bench:vanilla.accordion": VanillaAccordionHydrationProps;
        "bench:vanilla.checkbox": VanillaCheckboxHydrationProps;
        "bench:vanilla.input": VanillaInputHydrationProps;
        "bench:vanilla.select": VanillaSelectHydrationProps;
    }
}

export type ComboboxInputBehavior = 'autohighlight' | 'autocomplete' | 'none';
export type ComboboxSelectionBehavior = 'clear' | 'replace' | 'preserve';
export type DialogRole = 'dialog' | 'alertdialog';
export type FileUploadCapture = 'user' | 'environment';
export type ListCollection = {
items: Record<string | number, Record<string | number, any> | object>,
size: number,
first: string | null,
last: string | null,
itemToValueKey: string | null,
itemToStringKey: string | null,
isItemDisabledKey: string | null,
groupByKey: string | null,
groupSort: string[] | string | null,
};
export type NumberInputMode = 'text' | 'tel' | 'numeric' | 'decimal';
export type Orientation = 'horizontal' | 'vertical';
export type SliderOrigin = 'start' | 'center' | 'end';
export type SliderThumbAlignment = 'contain' | 'center';
export type SliderThumbCollisionBehavior = 'none' | 'push' | 'swap';
export type TabsActivationMode = 'automatic' | 'manual';
export type TextareaSubmitOn = 'enter' | 'mod+enter';
